// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBctFaejFuO3-wBH9VOkp192pug8LjVlpw',
    appId: '1:723181148402:web:99521f11ee25b235ad586b',
    messagingSenderId: '723181148402',
    projectId: 'instagram-105f8',
    authDomain: 'instagram-105f8.firebaseapp.com',
    storageBucket: 'instagram-105f8.firebasestorage.app',
    measurementId: 'G-H8CX2JVL6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFQJgs5YJ5R5Ueaf84jG0Hvjrg9ZO3oI',
    appId: '1:723181148402:android:626dafb2eb832ebbad586b',
    messagingSenderId: '723181148402',
    projectId: 'instagram-105f8',
    storageBucket: 'instagram-105f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAid83QqpLq3JJ88yCOBCet9Yc1Hu_OG-Q',
    appId: '1:723181148402:ios:d7b8df218326c278ad586b',
    messagingSenderId: '723181148402',
    projectId: 'instagram-105f8',
    storageBucket: 'instagram-105f8.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAid83QqpLq3JJ88yCOBCet9Yc1Hu_OG-Q',
    appId: '1:723181148402:ios:d7b8df218326c278ad586b',
    messagingSenderId: '723181148402',
    projectId: 'instagram-105f8',
    storageBucket: 'instagram-105f8.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBctFaejFuO3-wBH9VOkp192pug8LjVlpw',
    appId: '1:723181148402:web:af7f537c9858e03fad586b',
    messagingSenderId: '723181148402',
    projectId: 'instagram-105f8',
    authDomain: 'instagram-105f8.firebaseapp.com',
    storageBucket: 'instagram-105f8.firebasestorage.app',
    measurementId: 'G-LPT6LNKN3C',
  );
}
